version: "3.7"
services:
  web:
    build: .
    container_name: fund2
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/.ssh:/root/.ssh
      - /tmp/fund3.sqlite3:/Project/demo/fund/fund3.sqlite3
      - /tmp/files:/Project/demo/fund/static/files
    ports:
      - "8090:8090"
    privileged: true

    deploy:
      restart_policy:
        condition: on-failure